name: CI-Ubuntu-Ninja-Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clang: [20, 21]

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.0.3'

    - name: Setup SFML development libraries
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libfreetype-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev
      shell: bash
    
    - name: Install Clang ${{ matrix.clang }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.clang }}
      shell: bash

    - name: Check cmake version
      run: cmake --version

    - name: Configure CMake
      run: |
        cmake -B "${{env.BUILD_DIR}}" -G Ninja -D CMAKE_C_COMPILER=clang-${{ matrix.clang }} -D CMAKE_CXX_COMPILER=clang++-${{ matrix.clang }} -D CMAKE_CXX_STANDARD=23 -D CMAKE_CXX_STANDARD_REQUIRED=ON .
      shell: bash

    - name: Build
      run: |
        cmake --build "${{env.BUILD_DIR}}"
      shell: bash

    # Once CMake is updated to 4+, this can be uncommented
    # Github Actions don't have X server and therefore
    # some tests cannot pass, so we need to exclude them
    #- name: Test
    #  working-directory: ${{env.BUILD_DIR}}
    #  run: |
    #    ctest --rerun-failed --output-on-failure -- ~[App]
    #  shell: bash
