name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.26.1'

    - name: Check cmake version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{env.BUILD_DIR}}"
        cd "${{env.BUILD_DIR}}"
        cmake .. -D ENABLE_TESTS=OFF ENABLE_EXAMPLES=OFF ENABLE_SANDBOX=OFF
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build . --config Debug
        cmake --build . --config Release
      shell: cmd

    - name: Pack
      working-directory: ${{env.BUILD_DIR}}
      run: cpack
      
    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.event.repository.name}}
        path: ${{env.BUILD_DIR}}/*.zip
        retention-days: 5
